export const UPDATE_ACTIVE_PAGE = 'UPDATE_ACTIVE_PAGE';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const HIDE_MAIN_COMPONENT = 'HIDE_MAIN_COMPONENT';
export const GET_NEXT_SLIDE = 'GET_NEXT_SLIDE';
export const GET_PREVIOUS_SLIDE = 'GET_PREVIOUS_SLIDE';
